name: Reusable Build Workflow

on:
  workflow_call:  

jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Run script from Original workflow
        run: echo "Hi, We are testing the reusable-workflow on github actions"
